import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { isLoaded, isSignedIn, user } = useUser();
  const { data } = api.post.getAll.useQuery();
  console.log(data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#fff] to-[#15162c]">

        {isSignedIn ? <SignInButton /> : null}

        {isLoaded ? <SignOutButton /> : null}

        {data ?
          data?.map((post) => (
            <div key={`${post.content}_${post.id}`}>
              <h1>{post.content}</h1>
            </div>
          ))
          :
          <h1>No Data Available</h1>
        }

        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
